"""Transcribed BPZ tables at aa21eeb; validate all compatibility independently."""
from common import *
def rows(**kw):return {a:kw.get(a,'').split()for a in ABC}
TABLES['T3a']=rows(B='AHN ANV BAH BBB BDV BHD BVA DNH DVN HDN HNA VAN VND',N='AAN ADN ANA AND DAN DDN DNA DND NAA NAD NDA NDD NNN',A='AAA AAD ADA ADD ANN NAN NNA',D='DAA DAD DDA DDD DNN NDN NND',O='OAA OAD ODA ODD',H='HAA HAD HDA HDD HNN NHN NNH',V='NNV NVN VAA VAD VDA VDD VNN')
TABLES['T3b']=rows(B='BBB BHA NAV NDH NVD ABH AHN AHD DBV DVN DVD HND HDN HDD VNA VAB VDA',N='BVD NNN NVA ANH ADH AHN DNV DDH DHN HVD',A='NBA NAN ABB AAV AHA',D='NBD NDN DBB DAV DHA',H='NNH NHN HNN HVV',V='NNV NVN VNN VVV')
TABLES['T3e']=rows(B='AHN BAH BBB BDV BHD BVA DVN HDN HNA VAN VND',N='AAN AHN DAN DDN HNA NAA NAD NDA NDD NNN',A='AAA AAD ADA ADD ANN BNA HND NAN',D='AND DAA DAD DDA DDD DNN NDN NND',H='BNH HAA HAD HDD HHA HNN NHN',V='ANV DNH NNV NVN VAA VAD VDA VDD VNN')
TABLES['T3f']=rows(B='AHD AHN BAH BBB BDV BVA HDB HHH HNA NHD VND',N='AHB BHH DHA HDD HNA NAA NAH NHA NNN VHV',A='AAA AAH ABN BNA HHN HNH NAN',D='AND DAA DAD DBN NDN NND',H='BNH HAB HAV HNN NHN',V='ANV DNH DVN NNV NVN VAB VAV VNN')
TABLES['T3g']=copy.deepcopy(TABLES['T3f']);TABLES['T3g']['B']='AHN BAH BBB BDV BHD BVA HDN HNA VHA VHH VND'.split();TABLES['T3g']['D']='AND DAA DAH DBN NDN NND'.split()
TABLES['T3h']={a:TABLES['T3b'][a.translate(REFLECT)]for a in ABC}
TABLES['K4a']='BBBB BNVB BAHB BDVB BHNB BHDB BVAB NBBV NNVH NAVH NDHH NHNH NHAH NVDV ABBV ANHH AAVH ADHH AHAH AVNH AVDH DBBH DNVV DAVV DDHV DHNV DHAV DVDV HBBA HNVD HAHD HAVN HDHN HDVD HHNN HHND HHAN HHDD HVAD HVDN VBBN VBBD VNVN VNVA VAHA VDVA VHDA VVNA VVAA'.split()
TABLES['K4b']='AAAV AANV ABHA AHAA AHAN AHNA AHNN ANAV ANDH ANHN ANNH AVDB BADH BAVN BBBB BBVD BDBH BDHN BHHH BVAD BVND DAVA DHHA DNBV DNVA DNVN DVBA DVBN HABH HBDB HBVH HDAB HDNB HNND HVHD HVHN NAAV NANV NBHA NHAN NHBA NNAV NNDH NNNV NNVN NVDN NVHA NVNN VAAB VANB VDDH VHAH VHNH VNAB VNNA VNNN VVHV'.split()
if __name__=='__main__':
 for k,t in TABLES.items():print(k,'ADMISSIBLE',admissible(t),sum(map(len,t.values()))if isinstance(t,dict)else len(t))
 Path(__file__).with_name('extended_tables.json').write_text(json.dumps(TABLES,indent=2)+'\n')
