/- Generated only after the real axiom names have been read from Lean output.
This audit validates declarations; it introduces no mathematical assumptions.
The template itself was not compiled in the authoring session. -/
import ShannonBounds.C11AuxiliaryTrade
import Lean

set_option pp.fullNames true
set_option pp.universes true

open Lean Elab Command

elab "#check_native_bool_axiom " s:str : command => do
  let mut name := Name.anonymous
  for part in s.getString.splitOn "." do
    match part.toNat? with
    | some k => name := Name.num name k
    | none => name := Name.str name part
  let env ← getEnv
  match env.find? name with
  | some (.axiomInfo info) =>
    if info.isUnsafe then
      throwError "Unsafe native axiom: {name}"
    unless info.type.isAppOfArity ``Eq 3 do
      throwError "Native axiom is not an equality: {name}"
    let args := info.type.getAppArgs
    unless args[0]!.isConstOf ``Bool && args[2]!.isConstOf ``Bool.true do
      throwError "Native axiom is not a Bool equality to true: {name}"
    if args[1]!.hasFVar || args[1]!.hasMVar || args[1]!.hasLooseBVars then
      throwError "Native axiom expression is not closed: {name}"
    logInfo m!"NATIVE_BOOL_AXIOM_CHECKED: {name}"
    logInfo m!"NATIVE_BOOL_AXIOM_TYPE: {info.type}"
  | _ => throwError "Missing axiom declaration: {name}"

#check_native_bool_axiom "ShannonBounds.BaseC11.IlenCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.Iset._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.XcFalseLenCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.XcTrueLenCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.XlenCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.Xset._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.altInjCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.altNotCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.epParentCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.pFalseCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.pTrueCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.pairConflict._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.pairwiseOK_I._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.pairwiseOK_X._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.portsCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.portsLenCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.portsSet._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.privCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.sconf_iff_conflict._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.sconf_refl._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.sconf_symm._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.BaseC11.sepCheck._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.S3mix._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.S3mix._native.native_decide.ax_2"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.T3mix_eq_row_hybrid._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.decimal_lower_integer._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.stepx27._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.strictly_larger._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.C11AuxiliaryTrade.terminal_value._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb10._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb11._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb12._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb13._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb2._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb3._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb4._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb5._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb6._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb7._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb8._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepb9._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepg3._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph4._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph5._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph6._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph7._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph8._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.steph9._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepp11._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_1"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_2"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_3"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_4"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_5"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_6"
#check_native_bool_axiom "ShannonBounds.CertC11.stepx29._native.native_decide.ax_1_7"
#check_native_bool_axiom "ShannonBounds.Substitutions.S2b._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.Substitutions.S2b._native.native_decide.ax_2"
#check_native_bool_axiom "ShannonBounds.Substitutions.S3c._native.native_decide.ax_1"
#check_native_bool_axiom "ShannonBounds.Substitutions.S3c._native.native_decide.ax_2"
#check_native_bool_axiom "ShannonBounds.TerminalCodes.K3a._native.native_decide.ax_1"
